<classSpecifier>::=struct Identifier { } <initDeclarator> ;|class Identifier { } <initDeclarator> ;
<initDeclarator>::=Identifier = <initializerClause>
<initializerClause>::=<initializerClause> <initializerClause>|{ }|( <theTypeId> )
<theTypeId>::=const <parametersAndQualifiers>
<parametersAndQualifiers>::=Identifier|Identifier &|Identifier &&